"""Russian UI role labels; source catalog names and instructions remain unchanged."""

ROLE_NAMES_RU = {
    "academic-anthropologist": "Антрополог",
    "academic-geographer": "Географ",
    "academic-historian": "Историк",
    "academic-narratologist": "Исследователь повествования",
    "academic-psychologist": "Психолог",
    "academic-statistician": "Статистик",
    "design-brand-guardian": "Хранитель бренда",
    "design-image-prompt-engineer": "Специалист по запросам для генерации изображений",
    "design-inclusive-visuals-specialist": "Специалист по инклюзивному визуальному контенту",
    "design-persona-walkthrough": "Специалист по проверке пользовательских сценариев",
    "design-ui-designer": "Дизайнер интерфейсов",
    "design-ui-finish-gate-reviewer": "Эксперт по финальной проверке интерфейса",
    "design-ux-architect": "Архитектор пользовательского опыта",
    "design-ux-researcher": "Исследователь пользовательского опыта",
    "design-visual-storyteller": "Специалист по визуальным историям",
    "design-whimsy-injector": "Дизайнер творческих деталей",
    "engineering-ai-data-remediation-engineer": "Инженер по восстановлению данных для ИИ",
    "engineering-ai-engineer": "Инженер искусственного интеллекта",
    "engineering-api-platform-engineer": "Инженер платформы API",
    "engineering-ats-validator-architect": "Архитектор проверки систем подбора персонала",
    "engineering-autonomous-optimization-architect": "Архитектор автономной оптимизации",
    "engineering-backend-architect": "Архитектор серверной части",
    "engineering-china-network-engineer": "Инженер сетевого оборудования Китая",
    "engineering-cms-developer": "Разработчик систем управления контентом",
    "engineering-code-reviewer": "Эксперт по проверке кода",
    "engineering-codebase-onboarding-engineer": "Инженер по знакомству с кодовой базой",
    "engineering-data-engineer": "Инженер данных",
    "engineering-data-visualization-engineer": "Инженер визуализации данных",
    "engineering-database-optimizer": "Специалист по оптимизации баз данных",
    "engineering-database-reliability-engineer": "Инженер надёжности баз данных",
    "engineering-desktop-app-engineer": "Разработчик настольных приложений",
    "engineering-developer-tooling-engineer": "Инженер инструментов разработки",
    "engineering-devops-automator": "Инженер автоматизации разработки и эксплуатации",
    "engineering-drupal-performance": "Инженер производительности Drupal",
    "engineering-drupal-shopping-cart": "Инженер электронной торговли Drupal",
    "engineering-email-intelligence-engineer": "Инженер интеллектуальной обработки почты",
    "engineering-embedded-firmware-engineer": "Разработчик прошивок встроенных систем",
    "engineering-feishu-integration-developer": "Разработчик интеграций Feishu",
    "engineering-filament-optimization-specialist": "Специалист по оптимизации Filament",
    "engineering-finops-engineer": "Инженер управления облачными расходами",
    "engineering-frontend-developer": "Разработчик клиентской части",
    "engineering-gaussdb-expert": "Эксперт по GaussDB",
    "engineering-git-workflow-master": "Эксперт по рабочим процессам Git",
    "engineering-i18n-engineer": "Инженер интернационализации",
    "engineering-identity-access-engineer": "Инженер идентификации и управления доступом",
    "engineering-incident-response-commander": "Руководитель реагирования на инциденты",
    "engineering-iot-fleet-engineer": "Инженер управления устройствами интернета вещей",
    "engineering-it-service-manager": "Менеджер ИТ-сервисов",
    "engineering-knowledge-graph-engineer": "Инженер графов знаний",
    "engineering-llm-post-training-engineer": "Инженер дообучения языковых моделей",
    "engineering-minimal-change-engineer": "Инженер точечных изменений",
    "engineering-mobile-app-builder": "Разработчик мобильных приложений",
    "engineering-mobile-release-engineer": "Инженер выпуска мобильных приложений",
    "engineering-multi-agent-systems-architect": "Архитектор многоагентных систем",
    "engineering-network-engineer": "Сетевой инженер",
    "engineering-orgscript-engineer": "Разработчик OrgScript",
    "engineering-payments-billing-engineer": "Инженер платежей и биллинга",
    "engineering-pdf-engine-architect": "Архитектор системы формирования PDF",
    "engineering-platform-engineer": "Инженер внутренней платформы разработки",
    "engineering-privacy-engineer": "Инженер защиты персональных данных",
    "engineering-prompt-engineer": "Инженер запросов к языковым моделям",
    "engineering-rag-pipeline-engineer": "Инженер поиска и генерации на основе данных",
    "engineering-rapid-prototyper": "Разработчик быстрых прототипов",
    "engineering-realtime-collaboration-engineer": "Инженер совместной работы в реальном времени",
    "engineering-rust-refactoring-specialist": "Специалист по рефакторингу Rust",
    "engineering-search-relevance-engineer": "Инженер качества поиска",
    "engineering-section-508-specialist": "Специалист по доступности Section 508",
    "engineering-senior-developer": "Ведущий разработчик",
    "engineering-servicenow-developer-mentor": "Разработчик и наставник ServiceNow",
    "engineering-software-architect": "Архитектор программного обеспечения",
    "engineering-solidity-smart-contract-engineer": "Разработчик смарт-контрактов Solidity",
    "engineering-sre": "Инженер надёжности сервисов",
    "engineering-technical-writer": "Технический писатель",
    "engineering-universal-document-compiler": "Архитектор универсального компилятора документов",
    "engineering-uswds-developer": "Разработчик дизайн-системы USWDS",
    "engineering-video-streaming-engineer": "Инженер потокового видео",
    "engineering-voice-ai-integration-engineer": "Инженер интеграции голосового ИИ",
    "engineering-webassembly-engineer": "Разработчик WebAssembly",
    "engineering-wechat-mini-program-developer": "Разработчик мини-приложений WeChat",
    "engineering-wordpress-performance": "Инженер производительности WordPress",
    "engineering-wordpress-shopping-cart": "Инженер электронной торговли WordPress",
    "finance-bookkeeper-controller": "Бухгалтер и финансовый контролёр",
    "finance-financial-analyst": "Финансовый аналитик",
    "finance-fpa-analyst": "Аналитик финансового планирования",
    "finance-investment-researcher": "Исследователь инвестиций",
    "finance-tax-strategist": "Стратег налогового планирования",
    "blender-addon-engineer": "Разработчик дополнений Blender",
    "economy-designer": "Дизайнер игровой экономики",
    "game-audio-engineer": "Инженер игрового звука",
    "game-designer": "Игровой дизайнер",
    "godot-gameplay-scripter": "Разработчик игровой логики Godot",
    "godot-multiplayer-engineer": "Разработчик сетевой игры Godot",
    "godot-shader-developer": "Разработчик шейдеров Godot",
    "level-designer": "Дизайнер игровых уровней",
    "narrative-designer": "Дизайнер игровых историй",
    "roblox-avatar-creator": "Создатель аватаров Roblox",
    "roblox-experience-designer": "Дизайнер игровых сценариев Roblox",
    "roblox-systems-scripter": "Разработчик игровых систем Roblox",
    "technical-artist": "Технический художник",
    "unity-architect": "Архитектор Unity",
    "unity-editor-tool-developer": "Разработчик инструментов редактора Unity",
    "unity-multiplayer-engineer": "Разработчик сетевой игры Unity",
    "unity-shader-graph-artist": "Художник шейдеров Unity",
    "unreal-multiplayer-architect": "Архитектор сетевой игры Unreal Engine",
    "unreal-systems-engineer": "Инженер игровых систем Unreal Engine",
    "unreal-technical-artist": "Технический художник Unreal Engine",
    "unreal-world-builder": "Создатель игровых миров Unreal Engine",
    "gis-3d-scene-developer": "Разработчик трёхмерных геосцен",
    "gis-analyst": "Геоинформационный аналитик",
    "gis-bim-specialist": "Специалист по интеграции строительных и геоданных",
    "gis-cartography-designer": "Дизайнер карт",
    "gis-drone-reality-mapping": "Специалист по картографированию с дронов",
    "gis-geoai-ml-engineer": "Инженер машинного обучения для геоданных",
    "gis-geoprocessing-specialist": "Специалист по обработке геоданных",
    "gis-qa-engineer": "Инженер качества геоданных",
    "gis-solution-engineer": "Инженер геоинформационных решений",
    "gis-spatial-data-engineer": "Инженер пространственных данных",
    "gis-spatial-data-scientist": "Исследователь пространственных данных",
    "gis-technical-consultant": "Технический консультант по геоинформационным системам",
    "gis-web-gis-developer": "Разработчик картографических веб-приложений",
    "healthcare-clinical-evidence-agent": "Специалист по клиническим доказательствам",
    "healthcare-innovation-strategist": "Стратег инноваций в здравоохранении",
    "healthcare-sovereign-health-systems-agent": "Специалист по государственным системам здравоохранения",
    "marketing-aeo-foundations": "Архитектор продвижения в поисковых ответах",
    "marketing-agentic-search-optimizer": "Специалист по продвижению в агентном поиске",
    "marketing-ai-citation-strategist": "Стратег упоминаний в ответах ИИ",
    "marketing-app-store-optimizer": "Специалист по продвижению в магазинах приложений",
    "marketing-baidu-seo-specialist": "Специалист по поисковому продвижению в Baidu",
    "marketing-bilibili-content-strategist": "Контент-стратег Bilibili",
    "marketing-book-co-author": "Соавтор книги",
    "marketing-carousel-growth-engine": "Стратег продвижения через карусели",
    "marketing-china-ecommerce-operator": "Менеджер электронной торговли в Китае",
    "marketing-china-market-localization-strategist": "Стратег локализации для рынка Китая",
    "marketing-content-creator": "Создатель контента",
    "marketing-cross-border-ecommerce": "Специалист по международной электронной торговле",
    "marketing-developer-community-builder": "Менеджер сообщества разработчиков",
    "marketing-douyin-strategist": "Стратег продвижения в Douyin",
    "marketing-email-strategist": "Стратег почтового маркетинга",
    "marketing-global-podcast-strategist": "Стратег международных подкастов",
    "marketing-growth-hacker": "Специалист по росту продукта",
    "marketing-instagram-curator": "Контент-куратор Instagram",
    "marketing-kuaishou-strategist": "Стратег продвижения в Kuaishou",
    "marketing-linkedin-content-creator": "Создатель контента LinkedIn",
    "marketing-livestream-commerce-coach": "Наставник по продажам в прямых эфирах",
    "marketing-multi-platform-publisher": "Менеджер публикаций на разных площадках",
    "marketing-podcast-strategist": "Стратег подкастов",
    "marketing-pr-communications-manager": "Менеджер связей с общественностью",
    "marketing-private-domain-operator": "Менеджер собственных каналов работы с клиентами",
    "marketing-reddit-community-builder": "Менеджер сообщества Reddit",
    "marketing-seo-specialist": "Специалист по поисковому продвижению",
    "marketing-short-video-editing-coach": "Наставник по монтажу коротких видео",
    "marketing-social-media-strategist": "Стратег социальных сетей",
    "marketing-tiktok-strategist": "Стратег продвижения в TikTok",
    "marketing-twitter-engager": "Специалист по общению с аудиторией X / Twitter",
    "marketing-video-optimization-specialist": "Специалист по оптимизации видео",
    "marketing-wechat-official-account": "Менеджер официального аккаунта WeChat",
    "marketing-weibo-strategist": "Стратег продвижения в Weibo",
    "marketing-x-twitter-intelligence-analyst": "Аналитик данных X / Twitter",
    "marketing-xiaohongshu-specialist": "Специалист по продвижению в Xiaohongshu",
    "marketing-zhihu-strategist": "Стратег продвижения в Zhihu",
    "paid-media-auditor": "Аудитор платной рекламы",
    "paid-media-creative-strategist": "Стратег рекламных материалов",
    "paid-media-paid-social-strategist": "Стратег рекламы в социальных сетях",
    "paid-media-ppc-strategist": "Стратег контекстной рекламы",
    "paid-media-programmatic-buyer": "Специалист по автоматизированной закупке рекламы",
    "paid-media-search-query-analyst": "Аналитик поисковых запросов",
    "paid-media-tracking-specialist": "Специалист по отслеживанию и измерению рекламы",
    "product-behavioral-nudge-engine": "Специалист по поведенческим подсказкам",
    "product-dx-engineer": "Инженер удобства разработки",
    "product-feedback-synthesizer": "Аналитик обратной связи",
    "product-manager": "Менеджер продукта",
    "product-sprint-prioritizer": "Специалист по приоритетам спринта",
    "product-trend-researcher": "Исследователь тенденций",
    "project-management-experiment-tracker": "Координатор экспериментов",
    "project-management-jira-workflow-steward": "Координатор рабочих процессов Jira",
    "project-management-meeting-notes-specialist": "Специалист по протоколам встреч",
    "project-management-project-shepherd": "Руководитель проекта",
    "project-management-studio-operations": "Операционный менеджер студии",
    "project-management-studio-producer": "Продюсер студии",
    "project-manager-senior": "Ведущий руководитель проектов",
    "research-synthesist": "Специалист по обобщению исследований",
    "sales-account-strategist": "Стратег развития клиентов",
    "sales-coach": "Наставник по продажам",
    "sales-deal-strategist": "Стратег сделок",
    "sales-discovery-coach": "Наставник по выявлению потребностей клиентов",
    "sales-engineer": "Инженер предпродажной подготовки",
    "sales-offer-lead-gen-strategist": "Стратег предложений и привлечения клиентов",
    "sales-outbound-strategist": "Стратег исходящих продаж",
    "sales-pipeline-analyst": "Аналитик воронки продаж",
    "sales-proposal-strategist": "Стратег коммерческих предложений",
    "security-ai-generated-code-auditor": "Аудитор безопасности кода, созданного ИИ",
    "security-appsec-engineer": "Инженер безопасности приложений",
    "security-architect": "Архитектор безопасности",
    "security-blockchain-security-auditor": "Аудитор безопасности блокчейна",
    "security-cloud-security-architect": "Архитектор облачной безопасности",
    "security-compliance-auditor": "Аудитор соответствия требованиям",
    "security-incident-responder": "Специалист по реагированию на киберинциденты",
    "security-penetration-tester": "Специалист по тестированию на проникновение",
    "security-secrets-credential-engineer": "Инженер защиты секретов и учётных данных",
    "security-senior-secops": "Ведущий инженер эксплуатации безопасности",
    "security-threat-detection-engineer": "Инженер обнаружения угроз",
    "security-threat-intelligence-analyst": "Аналитик киберугроз",
    "macos-spatial-metal-engineer": "Инженер пространственной графики macOS и Metal",
    "terminal-integration-specialist": "Специалист по интеграции терминалов",
    "visionos-spatial-engineer": "Инженер пространственных интерфейсов visionOS",
    "xr-cockpit-interaction-specialist": "Специалист по управлению в виртуальной кабине",
    "xr-immersive-developer": "Разработчик иммерсивных приложений",
    "xr-interface-architect": "Архитектор интерфейсов расширенной реальности",
    "accounts-payable-agent": "Специалист по расчётам с поставщиками",
    "agentic-identity-trust": "Архитектор идентификации и доверия ИИ-агентов",
    "agents-orchestrator": "Координатор ИИ-агентов",
    "automation-governance-architect": "Архитектор управления автоматизацией",
    "business-strategist": "Бизнес-стратег",
    "change-management-consultant": "Консультант по управлению изменениями",
    "chief-financial-officer": "Финансовый директор",
    "corporate-training-designer": "Разработчик корпоративного обучения",
    "customer-service": "Специалист по обслуживанию клиентов",
    "customer-success-manager": "Менеджер по успеху клиентов",
    "data-consolidation-agent": "Специалист по объединению данных",
    "data-privacy-officer": "Ответственный за защиту персональных данных",
    "esg-sustainability-officer": "Специалист по устойчивому развитию",
    "government-digital-presales-consultant": "Консультант по продаже цифровых решений государству",
    "grant-writer": "Специалист по грантовым заявкам",
    "healthcare-aging-parent-care-companion": "Помощник по уходу за пожилыми родителями",
    "healthcare-customer-service": "Специалист по обслуживанию пациентов",
    "healthcare-marketing-compliance": "Специалист по соответствию медицинской рекламы требованиям",
    "hospitality-guest-services": "Специалист по обслуживанию гостей",
    "hr-onboarding": "Специалист по адаптации сотрудников",
    "identity-graph-operator": "Оператор графа идентификационных данных",
    "language-translator": "Переводчик",
    "legal-billing-time-tracking": "Специалист по учёту времени и юридическим счетам",
    "legal-client-intake": "Специалист по первичному приёму юридических клиентов",
    "legal-document-review": "Специалист по проверке юридических документов",
    "loan-officer-assistant": "Помощник кредитного специалиста",
    "lsp-index-engineer": "Инженер языковых серверов и индексации кода",
    "ma-integration-manager": "Менеджер интеграции при слияниях и поглощениях",
    "medical-billing-coding-specialist": "Специалист по медицинским счетам и кодированию",
    "operations-manager": "Операционный менеджер",
    "organizational-psychologist": "Организационный психолог",
    "personal-growth-mentor": "Наставник личностного развития",
    "real-estate-buyer-seller": "Помощник по покупке и продаже недвижимости",
    "recruitment-specialist": "Специалист по подбору персонала",
    "report-distribution-agent": "Специалист по распространению отчётов",
    "resume-tailor": "Специалист по адаптации резюме",
    "retail-customer-returns": "Специалист по возвратам в розничной торговле",
    "sales-data-extraction-agent": "Специалист по извлечению данных о продажах",
    "sales-outreach": "Специалист по первичному контакту в продажах",
    "specialized-chief-of-staff": "Руководитель штаба руководителя",
    "specialized-civil-engineer": "Инженер строительства",
    "specialized-codebase-archaeologist": "Исследователь истории кодовой базы",
    "specialized-cultural-intelligence-strategist": "Стратег межкультурного взаимодействия",
    "specialized-developer-advocate": "Специалист по работе с разработчиками",
    "specialized-document-generator": "Специалист по созданию документов",
    "specialized-fedramp-rmf-compliance": "Инженер соответствия FedRAMP и RMF",
    "specialized-focus-music-architect": "Архитектор музыки для концентрации",
    "specialized-french-consulting-market": "Консультант по французскому рынку ИТ-услуг",
    "specialized-korean-business-navigator": "Консультант по деловой культуре Кореи",
    "specialized-master-plan-architect": "Архитектор генерального плана",
    "specialized-mcp-builder": "Разработчик серверов MCP",
    "specialized-model-qa": "Специалист по качеству моделей",
    "specialized-pricing-analyst": "Аналитик ценообразования",
    "specialized-salesforce-architect": "Архитектор Salesforce",
    "specialized-strategy-duel-agent": "Специалист по стратегическим поединкам",
    "specialized-workflow-architect": "Архитектор рабочих процессов",
    "study-abroad-advisor": "Консультант по обучению за рубежом",
    "supply-chain-strategist": "Стратег цепочек поставок",
    "zk-steward": "Хранитель базы знаний",
    "support-analytics-reporter": "Специалист по аналитическим отчётам",
    "support-executive-summary-generator": "Специалист по управленческим сводкам",
    "support-finance-tracker": "Специалист по финансовому контролю",
    "support-infrastructure-maintainer": "Инженер сопровождения инфраструктуры",
    "support-legal-compliance-checker": "Специалист по юридическому соответствию",
    "support-support-responder": "Специалист службы поддержки",
    "testing-accessibility-auditor": "Аудитор доступности",
    "testing-api-tester": "Тестировщик API",
    "testing-evidence-collector": "Специалист по сбору доказательств качества",
    "testing-performance-benchmarker": "Специалист по тестированию производительности",
    "testing-reality-checker": "Эксперт по проверке готовности",
    "testing-test-automation-engineer": "Инженер автоматизации тестирования",
    "testing-test-results-analyzer": "Аналитик результатов тестирования",
    "testing-tool-evaluator": "Эксперт по оценке инструментов",
    "testing-workflow-optimizer": "Специалист по оптимизации рабочих процессов",
}


def role_name_ru(profile_id, source_name=""):
    """Unknown imported roles keep their source name until a UI translation is supplied."""
    return ROLE_NAMES_RU.get(profile_id, source_name)


ROLE_DESCRIPTIONS_RU = {
    "academic-anthropologist": "Исследует культуру, ритуалы, родство и верования; помогает создавать правдоподобные общества на основе этнографических методов.",
    "academic-geographer": "Проверяет рельеф, климат, ресурсы и расселение; создаёт географически согласованные миры и карты.",
    "academic-historian": "Проверяет историческую достоверность, периодизацию и материальную культуру по первичным и вторичным источникам.",
    "academic-narratologist": "Анализирует структуру истории, развитие персонажей и литературные приёмы с опорой на теорию повествования.",
    "academic-psychologist": "Помогает создавать психологически достоверных персонажей и взаимодействия с учётом поведения, мотивации и мышления.",
    "academic-statistician": "Проектирует количественные исследования и эксперименты; проверяет статистические выводы, случайность и систематические ошибки.",
    "design-brand-guardian": "Разрабатывает идентичность и позиционирование бренда; следит за согласованностью его визуального и смыслового образа.",
    "design-image-prompt-engineer": "Переводит визуальные идеи в подробные запросы для генерации фотографий и изображений с помощью ИИ.",
    "design-inclusive-visuals-specialist": "Помогает создавать культурно точные изображения и видео без стереотипов и систематических предубеждений ИИ.",
    "design-persona-walkthrough": "Проходит страницы глазами заданного пользователя; оценивает эмоции, понятность и препятствия на пути к целевому действию.",
    "design-ui-designer": "Создаёт доступные интерфейсы, дизайн-системы и библиотеки компонентов с согласованным визуальным стилем.",
    "design-ui-finish-gate-reviewer": "Проверяет готовность интерфейса по данным о продукте, согласованным требованиям к дизайну и качеству реализации.",
    "design-ux-architect": "Связывает пользовательский опыт с технической архитектурой; задаёт структуру интерфейса и рекомендации по реализации.",
    "design-ux-researcher": "Исследует поведение пользователей, проводит проверки удобства и формулирует рекомендации на основе данных.",
    "design-visual-storyteller": "Превращает сложную информацию в выразительные визуальные истории, мультимедийный контент и коммуникацию бренда.",
    "design-whimsy-injector": "Добавляет характер, игровые детали и приятные неожиданные взаимодействия в пользовательский опыт бренда.",
    "engineering-ai-data-remediation-engineer": "Выявляет и исправляет аномалии в потоках данных с помощью локальных моделей и детерминированных правил восстановления.",
    "engineering-ai-engineer": "Разрабатывает, развёртывает и интегрирует модели машинного обучения и интеллектуальные функции в приложения.",
    "engineering-api-platform-engineer": "Проектирует публичные и партнёрские API: контракты, версии, SDK, авторизацию, ограничения запросов и портал разработчика.",
    "engineering-ats-validator-architect": "Проектирует проверку систем подбора персонала и разбора резюме: поисковые алгоритмы, структуру PDF и соответствие требованиям.",
    "engineering-autonomous-optimization-architect": "Проверяет производительность API в фоновом режиме и ограничивает риски безопасности и неконтролируемые расходы.",
    "engineering-backend-architect": "Проектирует серверные приложения, базы данных, API и облачную инфраструктуру с учётом масштаба, безопасности и скорости.",
    "engineering-china-network-engineer": "Настраивает маршрутизацию, коммутаторы и межсетевые экраны Huawei, H3C, Ruijie и Hillstone для развёртываний в Китае.",
    "engineering-cms-developer": "Создаёт темы, плагины и модули Drupal и WordPress; проектирует структуру контента и системы управления сайтом.",
    "engineering-code-reviewer": "Проверяет корректность, поддерживаемость, безопасность и производительность кода; даёт конкретные рекомендации по исправлению.",
    "engineering-codebase-onboarding-engineer": "Помогает разработчикам разобраться в незнакомом проекте: читает код, прослеживает выполнение и объясняет подтверждённые факты.",
    "engineering-data-engineer": "Строит надёжные потоки загрузки и обработки данных, аналитические хранилища и масштабируемую инфраструктуру данных.",
    "engineering-data-visualization-engineer": "Подбирает графики и создаёт доступные интерактивные визуализации с честным отображением данных и эффективным рендерингом.",
    "engineering-database-optimizer": "Оптимизирует схемы, запросы, индексы и производительность PostgreSQL, MySQL и современных облачных баз данных.",
    "engineering-database-reliability-engineer": "Обеспечивает доступность баз данных: репликацию, резервное копирование, восстановление, безопасные миграции и переключение при сбоях.",
    "engineering-desktop-app-engineer": "Создаёт приложения Electron и Tauri с безопасным обменом между процессами, обновлениями и интеграцией с операционной системой.",
    "engineering-developer-tooling-engineer": "Разрабатывает удобные командные инструменты и внутренние платформы с понятными командами, ошибками и установкой на разных системах.",
    "engineering-devops-automator": "Автоматизирует инфраструктуру, сборку, тестирование, развёртывание и эксплуатацию облачных приложений.",
    "engineering-drupal-performance": "Ускоряет Drupal: кеширование, запросы, изображения, ресурсы страницы, CDN и серверные настройки.",
    "engineering-drupal-shopping-cart": "Разрабатывает магазины Drupal Commerce: каталог, оплату, оформление заказов, налоги и акции.",
    "engineering-email-intelligence-engineer": "Извлекает структурированные данные из переписки для ИИ-агентов и автоматизированных процессов.",
    "engineering-embedded-firmware-engineer": "Разрабатывает прошивки микроконтроллеров и встроенных систем с использованием ESP32, ARM, Arduino и операционных систем реального времени.",
    "engineering-feishu-integration-developer": "Создаёт ботов, мини-приложения, согласования и автоматизации на платформе Feishu / Lark.",
    "engineering-filament-optimization-specialist": "Перестраивает административные интерфейсы Filament для удобной и эффективной работы с данными.",
    "engineering-finops-engineer": "Анализирует и оптимизирует расходы AWS, GCP и Azure: ресурсы, обязательства, хранение, передачу данных и стоимость продукта.",
    "engineering-frontend-developer": "Реализует пользовательские интерфейсы на React, Vue и Angular; оптимизирует скорость и поведение веб-приложений.",
    "engineering-gaussdb-expert": "Проектирует и оптимизирует транзакционные базы GaussDB: схемы, распределённые таблицы, запросы, индексы и хранение.",
    "engineering-git-workflow-master": "Настраивает рабочие процессы Git, ветвление, коммиты, перебазирование и совместную работу с автоматическими проверками.",
    "engineering-i18n-engineer": "Локализует приложения: сообщения, формы множественного числа, направления текста, даты, числа и проверку переводов.",
    "engineering-identity-access-engineer": "Проектирует вход, корпоративную аутентификацию, сессии, ключи доступа и разграничение прав пользователей.",
    "engineering-incident-response-commander": "Координирует работу при производственных инцидентах, восстановление сервиса, разбор причин и улучшение дежурств.",
    "engineering-iot-fleet-engineer": "Управляет парками устройств интернета вещей: подключением, идентификацией, телеметрией и обновлениями с откатом.",
    "engineering-it-service-manager": "Организует каталог ИТ-услуг, инциденты, изменения, уровни обслуживания и улучшение процессов по ITIL.",
    "engineering-knowledge-graph-engineer": "Структурирует сущности и связи в графах знаний для поиска контекста, согласованности данных и снижения ошибок ИИ.",
    "engineering-llm-post-training-engineer": "Организует дообучение языковых моделей, оптимизацию предпочтений, оценку результатов и условия выпуска новой версии.",
    "engineering-minimal-change-engineer": "Исправляет задачу минимальными изменениями кода; ограничивает объём правок и избегает лишней переработки архитектуры.",
    "engineering-mobile-app-builder": "Создаёт нативные и кроссплатформенные мобильные приложения для iOS и Android.",
    "engineering-mobile-release-engineer": "Готовит мобильные релизы: подпись, сборку, публикацию в магазинах, поэтапное развёртывание и контроль сбоев.",
    "engineering-multi-agent-systems-architect": "Проектирует многоагентные системы: связи ролей, обмен контекстом, доверие, восстановление и согласования с человеком.",
    "engineering-network-engineer": "Настраивает маршрутизацию, коммутацию и безопасность сетей Cisco, Juniper и Palo Alto; диагностирует сетевые проблемы.",
    "engineering-orgscript-engineer": "Проектирует грамматику OrgScript, разбор и проверку синтаксических деревьев и описаний бизнес-логики.",
    "engineering-payments-billing-engineer": "Интегрирует платежи, подписки и уведомления платёжных систем; обеспечивает идемпотентность, сверку и безопасную обработку.",
    "engineering-pdf-engine-architect": "Проектирует воспроизводимую генерацию PDF из HTML, размер страниц, доступность документов и редакторы печатных листов.",
    "engineering-platform-engineer": "Создаёт внутренние платформы и стандартные процессы, которые упрощают самостоятельную работу команд разработки.",
    "engineering-privacy-engineer": "Реализует защиту персональных данных в коде: минимизацию, согласия, удаление, псевдонимизацию и сроки хранения.",
    "engineering-prompt-engineer": "Создаёт, тестирует и улучшает запросы к языковым моделям для предсказуемого поведения в приложениях.",
    "engineering-rag-pipeline-engineer": "Строит поиск по данным для языковых моделей: разбиение документов, гибридный поиск, ранжирование и оценку качества.",
    "engineering-rapid-prototyper": "Быстро создаёт работающие прототипы и минимальные версии продуктов для проверки идей.",
    "engineering-realtime-collaboration-engineer": "Проектирует совместную работу в реальном времени, синхронизацию, присутствие пользователей и устойчивое переподключение.",
    "engineering-rust-refactoring-specialist": "Безопасно перерабатывает проекты Rust: переименования, модули, владение данными, обработку ошибок и исправления компилятора.",
    "engineering-search-relevance-engineer": "Настраивает Elasticsearch и OpenSearch: индексы, анализ текста, ранжирование и оценку качества поисковых результатов.",
    "engineering-section-508-specialist": "Проверяет и улучшает доступность сайтов и документов по Section 508 и WCAG, включая клавиатуру и программы чтения с экрана.",
    "engineering-senior-developer": "Реализует сложные приложения на Laravel, Livewire и FluxUI с продвинутыми стилями и интеграцией Three.js.",
    "engineering-servicenow-developer-mentor": "Разрабатывает и диагностирует ServiceNow: серверные правила, сценарии, процессы, запросы данных и права доступа.",
    "engineering-software-architect": "Проектирует программные системы, предметные модели и архитектурные решения для масштабируемого и поддерживаемого кода.",
    "engineering-solidity-smart-contract-engineer": "Разрабатывает смарт-контракты Solidity: архитектуру EVM, оптимизацию газа, обновления и безопасность протоколов.",
    "engineering-sre": "Улучшает надёжность сервисов: целевые показатели, наблюдаемость, испытания сбоев и сокращение ручной эксплуатационной работы.",
    "engineering-technical-writer": "Пишет понятную документацию разработчика: справочники API, инструкции, README и учебные материалы.",
    "engineering-universal-document-compiler": "Проектирует универсальную модель документов, автоматическую компоновку и синхронизацию текста с визуальным редактором.",
    "engineering-uswds-developer": "Создаёт доступные государственные интерфейсы на дизайн-системе USWDS с компонентами, темами и интеграцией в CMS.",
    "engineering-video-streaming-engineer": "Настраивает адаптивное потоковое видео: кодирование, HLS, DASH, защиту контента, доставку и качество воспроизведения.",
    "engineering-voice-ai-integration-engineer": "Создаёт обработку речи: подготовку аудио, распознавание, очистку текста, субтитры, разделение говорящих и интеграции.",
    "engineering-webassembly-engineer": "Компилирует Rust, C и C++ в WebAssembly; оптимизирует взаимодействие с JavaScript и выполнение на сервере.",
    "engineering-wechat-mini-program-developer": "Разрабатывает мини-приложения WeChat, интеграции API, платежи и сообщения по подписке.",
    "engineering-wordpress-performance": "Ускоряет WordPress: кеширование, запросы, изображения, CDN, настройки PHP и проверку влияния плагинов.",
    "engineering-wordpress-shopping-cart": "Создаёт магазины WooCommerce: каталог, оплату, оформление заказов, налоги, купоны и удобство покупки.",
    "finance-bookkeeper-controller": "Ведёт бухгалтерские операции, сверки, закрытие месяца и внутренний контроль для точных и проверяемых финансовых записей.",
    "finance-financial-analyst": "Строит финансовые модели, прогнозы и сценарии; превращает финансовые данные в основу управленческих решений.",
    "finance-fpa-analyst": "Готовит бюджеты, анализ отклонений и скользящие прогнозы для планирования и распределения ресурсов.",
    "finance-investment-researcher": "Исследует рынки, оценивает активы и инвестиционные риски; проводит проверку компаний и анализ портфелей.",
    "finance-tax-strategist": "Разрабатывает налоговые стратегии и трансфертное ценообразование с учётом требований разных юрисдикций.",
    "blender-addon-engineer": "Создаёт дополнения Blender на Python, проверки ресурсов, экспорт и автоматизацию повторяющихся операций.",
    "economy-designer": "Проектирует игровые валюты, поступления и расходы, монетизацию, контроль инфляции и баланс виртуальной экономики.",
    "game-audio-engineer": "Интегрирует игровой звук, адаптивную музыку и пространственное аудио с контролем производительности.",
    "game-designer": "Проектирует игровые механики, циклы действий и баланс; оформляет идеи в документ игрового дизайна.",
    "godot-gameplay-scripter": "Создаёт игровую логику Godot 4 на GDScript и C# с согласованной структурой узлов и сигналов.",
    "godot-multiplayer-engineer": "Реализует сетевые игры Godot 4: синхронизацию сцен, удалённые вызовы, транспорт и управление полномочиями.",
    "godot-shader-developer": "Создаёт шейдеры и визуальные эффекты Godot для двумерных и трёхмерных сцен; оптимизирует обработку изображения.",
    "level-designer": "Проектирует игровые уровни, темп, столкновения и повествование через окружение.",
    "narrative-designer": "Создаёт игровые истории, разветвлённые диалоги, устройство мира и повествование, связанное с механиками игры.",
    "roblox-avatar-creator": "Создаёт аватары и пользовательские предметы Roblox, настраивает аксессуары и текстуры и готовит публикацию.",
    "roblox-experience-designer": "Проектирует игровые сценарии Roblox, прогресс, удержание игроков и монетизацию.",
    "roblox-systems-scripter": "Разрабатывает игровые системы Roblox на Luau с безопасной клиент-серверной моделью и хранением данных.",
    "technical-artist": "Связывает художественные ресурсы с игровым движком: шейдеры, эффекты, уровни детализации и оптимизацию.",
    "unity-architect": "Проектирует модульные системы Unity на основе данных, независимых компонентов и разделения ответственности.",
    "unity-editor-tool-developer": "Автоматизирует редактор Unity: пользовательские окна, импорт ресурсов, свойства и процессы подготовки контента.",
    "unity-multiplayer-engineer": "Реализует сетевую игру Unity: подключение игроков, серверные полномочия, компенсацию задержек и синхронизацию.",
    "unity-shader-graph-artist": "Создаёт материалы и визуальные эффекты Unity с Shader Graph, HLSL и конвейерами URP / HDRP.",
    "unreal-multiplayer-architect": "Проектирует сетевые системы Unreal Engine: репликацию объектов, серверное управление, предсказание и выделенные серверы.",
    "unreal-systems-engineer": "Создаёт производительные системы Unreal Engine с C++, Blueprint, Nanite, Lumen и системой игровых способностей.",
    "unreal-technical-artist": "Настраивает художественный конвейер Unreal Engine: материалы, Niagara, процедурный контент и интеграцию ресурсов.",
    "unreal-world-builder": "Создаёт большие игровые миры Unreal Engine: ландшафты, растительность, разделение мира и потоковую загрузку уровней.",
    "gis-3d-scene-developer": "Создаёт интерактивные трёхмерные геосцены, рельеф и визуализацию облаков точек в браузере.",
    "gis-analyst": "Создаёт карты, управляет слоями, выполняет пространственные запросы и проверяет целостность геоданных.",
    "gis-bim-specialist": "Связывает строительные модели и геоданные: конвертацию Revit / IFC, внутренние карты, цифровые двойники и управление объектами.",
    "gis-cartography-designer": "Оформляет читаемые карты: цвета, подписи, типографику, базовые слои и визуальную иерархию для печати и веба.",
    "gis-drone-reality-mapping": "Обрабатывает снимки дронов в ортофотопланы, модели рельефа, облака точек и трёхмерные поверхности.",
    "gis-geoai-ml-engineer": "Применяет машинное обучение к спутниковым и аэроснимкам: обнаружению объектов, сегментации и классификации поверхности.",
    "gis-geoprocessing-specialist": "Автоматизирует обработку геоданных в ArcGIS Pro с Python, ArcPy, инструментами и пакетными процессами.",
    "gis-qa-engineer": "Проверяет топологию, метаданные, системы координат, точность и соответствие геоданных требованиям.",
    "gis-solution-engineer": "Создаёт работающие прототипы геоинформационных решений и проверяет их техническую реализуемость.",
    "gis-spatial-data-engineer": "Приводит геоданные к единому виду: форматы, системы координат, атрибуты и автоматизированные потоки загрузки.",
    "gis-spatial-data-scientist": "Анализирует пространственные закономерности с помощью статистических моделей, кластеризации и прогнозирования.",
    "gis-technical-consultant": "Переводит бизнес-задачи в геоинформационные решения, оценивает пробелы и разрабатывает технологические планы.",
    "gis-web-gis-developer": "Создаёт картографические веб-приложения, интерактивные панели, интеграции API и сервисы геоданных.",
    "healthcare-clinical-evidence-agent": "Оценивает обоснованность клинических утверждений и помогает описывать поддержку решений без присвоения диагностических полномочий.",
    "healthcare-innovation-strategist": "Формулирует стратегию и коммуникацию медицинских инноваций для клинической, инвестиционной, регуляторной и государственной аудитории.",
    "healthcare-sovereign-health-systems-agent": "Связывает медицинские технологии с национальными программами здравоохранения и планирует взаимодействие с государственными заказчиками.",
    "marketing-aeo-foundations": "Готовит сайт к обнаружению и чтению ИИ: структурирует контент, llms.txt, robots.txt и файлы для поисковых агентов.",
    "marketing-agentic-search-optimizer": "Проверяет выполнение задач ИИ-агентами на сайте и внедряет WebMCP для бронирования, покупок и регистрации.",
    "marketing-ai-citation-strategist": "Анализирует видимость бренда в ответах ИИ и предлагает изменения контента для корректных упоминаний и цитирования.",
    "marketing-app-store-optimizer": "Улучшает обнаружение приложения в магазинах, оформление страницы и превращение просмотров в установки.",
    "marketing-baidu-seo-specialist": "Продвигает сайты в Baidu с учётом китайских ключевых слов, мобильного поиска и местных требований.",
    "marketing-bilibili-content-strategist": "Планирует контент и развитие сообщества Bilibili с учётом культуры платформы и алгоритмов рекомендаций.",
    "marketing-book-co-author": "Помогает основателям и экспертам превращать голосовые заметки и идеи в структурированные главы книги от первого лица.",
    "marketing-carousel-growth-engine": "Проектирует и улучшает карусели TikTok и Instagram: анализ сайта, генерацию слайдов, публикацию и оценку результатов.",
    "marketing-china-ecommerce-operator": "Управляет магазинами Taobao, Tmall, Pinduoduo и JD: карточками товаров, прямыми эфирами, акциями и операциями.",
    "marketing-china-market-localization-strategist": "Адаптирует выход продукта на рынок Китая с учётом текущих тенденций и местных социальных площадок.",
    "marketing-content-creator": "Создаёт тексты, истории бренда и редакционные планы для кампаний на разных цифровых площадках.",
    "marketing-cross-border-ecommerce": "Планирует международную электронную торговлю: маркетплейсы, логистику, налоги, локализацию карточек и независимые магазины.",
    "marketing-developer-community-builder": "Развивает сообщества разработчиков, обсуждения и программы участников на Discord, GitHub и форумах.",
    "marketing-douyin-strategist": "Планирует короткие видео, прямые продажи и рост бренда в Douyin с учётом алгоритмов рекомендаций.",
    "marketing-email-strategist": "Проектирует почтовые кампании, сегментацию и автоматические цепочки по жизненному циклу клиента; контролирует доставку и измерение.",
    "marketing-global-podcast-strategist": "Развивает международные подкасты: позиционирование, контент, аудиторию, распространение и монетизацию.",
    "marketing-growth-hacker": "Проверяет гипотезы роста, оптимизирует воронки и находит масштабируемые каналы привлечения пользователей.",
    "marketing-instagram-curator": "Формирует визуальный стиль, контент разных форматов и взаимодействие с сообществом Instagram.",
    "marketing-kuaishou-strategist": "Развивает короткие видео и прямые продажи Kuaishou с опорой на доверие сообщества и локальную аудиторию.",
    "marketing-linkedin-content-creator": "Создаёт профессиональный контент LinkedIn для экспертного позиционирования, личного бренда и входящих обращений.",
    "marketing-livestream-commerce-coach": "Обучает ведущих торговых эфиров: сценариям, порядку товаров, работе с трафиком и анализу конверсии.",
    "marketing-multi-platform-publisher": "Адаптирует статьи для китайских площадок и готовит черновики публикаций для проверки человеком.",
    "marketing-podcast-strategist": "Планирует производство, продвижение и монетизацию подкастов для китайских аудиоплатформ.",
    "marketing-pr-communications-manager": "Планирует работу со СМИ, пресс-релизы, кризисную коммуникацию и защиту репутации бренда.",
    "marketing-private-domain-operator": "Развивает собственные клиентские каналы WeChat / WeCom: сообщества, сегментацию, мини-магазины и жизненный цикл клиента.",
    "marketing-reddit-community-builder": "Развивает присутствие бренда в сообществах Reddit через полезный контент и устойчивые отношения с аудиторией.",
    "marketing-seo-specialist": "Улучшает техническое состояние сайта, контент и поисковую репутацию для роста органического трафика.",
    "marketing-short-video-editing-coach": "Обучает монтажу коротких видео: композиции, цвету, звуку, эффектам, субтитрам и подготовке для разных площадок.",
    "marketing-social-media-strategist": "Создаёт кампании на профессиональных социальных площадках, развивает сообщества и экспертную коммуникацию.",
    "marketing-tiktok-strategist": "Разрабатывает контент и продвижение TikTok с учётом культуры, возможностей и алгоритмов платформы.",
    "marketing-twitter-engager": "Развивает общение с аудиторией X / Twitter, экспертное присутствие и содержательные цепочки публикаций.",
    "marketing-video-optimization-specialist": "Оптимизирует видео для YouTube: удержание аудитории, главы, идеи обложек и распространение на других площадках.",
    "marketing-wechat-official-account": "Развивает официальный аккаунт WeChat: контент, взаимодействие с подписчиками и конверсию.",
    "marketing-weibo-strategist": "Управляет продвижением Weibo: популярными темами, сообществами, настроениями аудитории и рекламой.",
    "marketing-x-twitter-intelligence-analyst": "Исследует публичные сигналы X / Twitter, тенденции и аккаунты для подтверждённых выводов об аудитории.",
    "marketing-xiaohongshu-specialist": "Создаёт визуальный контент и продвижение Xiaohongshu с учётом образа жизни, тенденций и культуры сообщества.",
    "marketing-zhihu-strategist": "Развивает экспертную репутацию бренда в Zhihu через ответы на вопросы и полезный контент.",
    "paid-media-auditor": "Проверяет рекламные аккаунты Google, Microsoft и Meta: структуру, отслеживание, ставки, материалы и аудитории.",
    "paid-media-creative-strategist": "Разрабатывает рекламные тексты, наборы материалов и эксперименты с креативами на основе данных о результатах.",
    "paid-media-paid-social-strategist": "Проектирует рекламу в социальных сетях от привлечения до повторного обращения с учётом площадки и аудитории.",
    "paid-media-ppc-strategist": "Проектирует поисковые, товарные и автоматизированные рекламные кампании, бюджеты и стратегии ставок.",
    "paid-media-programmatic-buyer": "Планирует закупку медийной рекламы, размещения и кампании по целевым компаниям на программных платформах.",
    "paid-media-search-query-analyst": "Анализирует поисковые запросы, намерения и минус-слова для сокращения неэффективных рекламных расходов.",
    "paid-media-tracking-specialist": "Настраивает измерение конверсий, теги, серверное отслеживание и модели атрибуции рекламных каналов.",
    "product-behavioral-nudge-engine": "Адаптирует ритм и стиль взаимодействия приложения к мотивации пользователя и успешному выполнению задач.",
    "product-dx-engineer": "Упрощает первые шаги разработчика: примеры SDK, начало работы, сообщения об ошибках и обратную связь.",
    "product-feedback-synthesizer": "Обобщает отзывы из разных каналов и превращает их в проверяемые приоритеты развития продукта.",
    "product-manager": "Управляет жизненным циклом продукта: исследованием, стратегией, планом развития, выходом на рынок и оценкой результатов.",
    "product-sprint-prioritizer": "Планирует спринты, приоритеты функций и распределение ресурсов с учётом ценности для бизнеса.",
    "product-trend-researcher": "Исследует тенденции рынка, конкурентов и новые возможности для продуктовой стратегии.",
    "project-management-experiment-tracker": "Организует эксперименты и A/B-проверки, отслеживает выполнение и оценивает подтверждение гипотез.",
    "project-management-jira-workflow-steward": "Связывает работу Jira с Git: прослеживаемыми коммитами, запросами на слияние и безопасной стратегией выпуска.",
    "project-management-meeting-notes-specialist": "Извлекает из записей встреч решения, действия и открытые вопросы в структурированную сводку.",
    "project-management-project-shepherd": "Координирует команды, сроки, ресурсы, риски и коммуникацию для доведения проекта до результата.",
    "project-management-studio-operations": "Организует ежедневную работу студии, координирует ресурсы и улучшает процессы взаимодействия команд.",
    "project-management-studio-producer": "Управляет творческими и техническими инициативами студии, ресурсами и портфелем проектов.",
    "project-manager-senior": "Превращает требования в задачи, учитывает опыт прошлых проектов и контролирует реалистичный объём работ.",
    "research-synthesist": "Оценивает источники и литературу; собирает структурированную картину того, что подтверждается доказательствами.",
    "sales-account-strategist": "Планирует развитие действующих клиентов, работу с заинтересованными сторонами и расширение долгосрочных отношений.",
    "sales-coach": "Обучает продавцов, разбирает звонки и сделки и улучшает качество воронки и прогнозов.",
    "sales-deal-strategist": "Оценивает сложные сделки B2B, конкурентную позицию и риски; разрабатывает стратегию выигрыша.",
    "sales-discovery-coach": "Помогает продавцам выявлять потребности: формулировать вопросы, оценивать разрыв и понимать мотивацию покупки.",
    "sales-engineer": "Проводит техническое выявление потребностей, создаёт демонстрации и проверочные прототипы для предпродажной подготовки.",
    "sales-offer-lead-gen-strategist": "Создаёт коммерческие предложения и полезные материалы для привлечения подходящих клиентов через разные каналы.",
    "sales-outbound-strategist": "Проектирует исходящие продажи на основе исследований, сигналов потребности и персонализированных последовательностей контактов.",
    "sales-pipeline-analyst": "Анализирует данные CRM: состояние воронки, скорость сделок, точность прогнозов и ранние признаки рисков.",
    "sales-proposal-strategist": "Создаёт убедительные коммерческие предложения и ответы на запросы с ясной ценностью и конкурентным позиционированием.",
    "security-ai-generated-code-auditor": "Проверяет приложения, созданные ИИ, на секреты в коде, ошибки доступа и внедрение инструкций; повторно проверяет исправления.",
    "security-appsec-engineer": "Встраивает безопасность в разработку: моделирование угроз, проверку кода, автоматические сканирования и обучение.",
    "security-architect": "Проектирует защиту систем: границы доверия, модель угроз, эшелонированные меры и оценку рисков.",
    "security-blockchain-security-auditor": "Проверяет смарт-контракты и блокчейн-приложения: уязвимости, формальную корректность и возможные способы эксплуатации.",
    "security-cloud-security-architect": "Проектирует безопасность AWS, Azure и GCP, нулевое доверие и защиту инфраструктуры, описанной кодом.",
    "security-compliance-auditor": "Готовит технические проверки соответствия SOC 2, ISO 27001, HIPAA и PCI-DSS и собирает подтверждающие материалы.",
    "security-incident-responder": "Расследует киберинциденты, сдерживает угрозы, координирует реагирование и разбирает причины для предотвращения повторений.",
    "security-penetration-tester": "Проводит разрешённые проверки на проникновение и оценку уязвимостей сетей, веб-приложений и облачной инфраструктуры.",
    "security-secrets-credential-engineer": "Управляет обнаружением, хранением, ротацией и защитой секретов и учётных данных с минимальными полномочиями.",
    "security-senior-secops": "Проверяет утечки секретов и меры безопасности приложений: доступ, токены, заголовки, входные данные и журналы.",
    "security-threat-detection-engineer": "Создаёт и настраивает правила SIEM, покрытие MITRE ATT&CK, поиск угроз и воспроизводимые проверки обнаружения.",
    "security-threat-intelligence-analyst": "Исследует группы атакующих и кампании, готовит отчёты об угрозах и правила для их выявления.",
    "macos-spatial-metal-engineer": "Создаёт высокопроизводительную трёхмерную графику и пространственные приложения macOS и Vision Pro на Swift и Metal.",
    "terminal-integration-specialist": "Интегрирует эмуляцию терминала и SwiftTerm в приложения Swift; оптимизирует отображение текста.",
    "visionos-spatial-engineer": "Разрабатывает пространственные интерфейсы visionOS, объёмные представления SwiftUI и оформление Liquid Glass.",
    "xr-cockpit-interaction-specialist": "Проектирует и разрабатывает управление в иммерсивных кабинах для сред расширенной реальности.",
    "xr-immersive-developer": "Создаёт браузерные приложения дополненной, виртуальной и расширенной реальности с использованием WebXR.",
    "xr-interface-architect": "Проектирует пространственные взаимодействия и интерфейсы для иммерсивных сред дополненной и виртуальной реальности.",
    "accounts-payable-agent": "Организует оплату поставщикам, подрядчикам и регулярных счетов через различные платёжные системы в агентных процессах.",
    "agentic-identity-trust": "Проектирует идентификацию и доверие между ИИ-агентами: подтверждение личности, полномочий и выполненных действий.",
    "agents-orchestrator": "Координирует полный процесс разработки, распределяет работу между агентами и управляет передачей результатов.",
    "automation-governance-architect": "Оценивает ценность, риски и поддерживаемость бизнес-автоматизаций до реализации, преимущественно в n8n.",
    "business-strategist": "Анализирует конкурентов, выход на рынок, бизнес-модели и организационные решения для устойчивого развития бизнеса.",
    "change-management-consultant": "Помогает организациям внедрять изменения, преодолевать сопротивление и закреплять новые процессы и культуру.",
    "chief-financial-officer": "Управляет распределением капитала, казначейством, финансовым планированием и отчётностью для инвесторов и совета директоров.",
    "corporate-training-designer": "Проектирует корпоративные программы обучения, развитие наставников и руководителей и оценку эффективности обучения.",
    "customer-service": "Обрабатывает вопросы, жалобы и обращения клиентов; передаёт сложные случаи нужным специалистам.",
    "customer-success-manager": "Помогает клиентам освоить продукт, оценивает состояние отношений, предотвращает отток и планирует продление и развитие.",
    "data-consolidation-agent": "Объединяет данные о продажах в актуальные отчёты по территориям, представителям и воронке.",
    "data-privacy-officer": "Разрабатывает программы защиты данных: учёт обработки, оценку воздействия, согласия, работу с поставщиками и реагирование на утечки.",
    "esg-sustainability-officer": "Разрабатывает программы устойчивого развития и ESG-отчётность, инициативы декарбонизации и согласование стратегии с требованиями.",
    "government-digital-presales-consultant": "Готовит цифровые решения для госзаказчиков Китая: анализ политики, конкурсные документы, прототипы и проверку местных требований.",
    "grant-writer": "Готовит грантовые заявки, бюджетные обоснования и отчётность для некоммерческих организаций и исследовательских проектов.",
    "healthcare-aging-parent-care-companion": "Помогает семье координировать уход за пожилыми родителями: встречи, лекарства, общение со специалистами и поддержку ухаживающих.",
    "healthcare-customer-service": "Помогает пациентам с записью, счетами, страховыми вопросами и жалобами, направляя клинические вопросы специалистам.",
    "healthcare-marketing-compliance": "Проверяет медицинскую рекламу для рынка Китая: содержание, ограничения площадок, риски и защиту данных пациентов.",
    "hospitality-guest-services": "Организует бронирование, заселение, услуги для гостей, работу с жалобами и последующее сопровождение.",
    "hr-onboarding": "Организует адаптацию сотрудников: документы, льготы, знакомство с культурой и поддержку от первого дня до первого года.",
    "identity-graph-operator": "Поддерживает общий граф идентификации, чтобы агенты согласованно определяли сущности даже при параллельной записи.",
    "language-translator": "Переводит между испанским и английским с учётом контекста, диалектов и тона повседневного и делового общения.",
    "legal-billing-time-tracking": "Организует учёт времени и юридические счета, описание работ, взыскание оплат и анализ расчётов.",
    "legal-client-intake": "Готовит первичный приём юридических клиентов: сбор сведений, проверку конфликтов, запись и сводку для юриста.",
    "legal-document-review": "Обобщает юридические документы, выявляет рискованные положения, сравнивает версии и проверяет соответствие требованиям.",
    "loan-officer-assistant": "Помогает кредитному специалисту: сбор данных и документов, предварительную оценку, сопровождение заявок и координацию сделки.",
    "lsp-index-engineer": "Создаёт системы анализа кода с оркестрацией языковых серверов и семантической индексацией.",
    "ma-integration-manager": "Планирует интеграцию после слияний и поглощений: готовность первого дня, первые сто дней, синергию и координацию направлений.",
    "medical-billing-coding-specialist": "Помогает с медицинским кодированием, счетами, страховыми требованиями, отказами и контролем доходного цикла.",
    "operations-manager": "Улучшает бизнес-процессы: планирование мощности, показатели, поставщиков и эффективность с помощью Lean и Six Sigma.",
    "organizational-psychologist": "Анализирует взаимодействие команды, психологическую безопасность, выгорание и состояние организационной культуры.",
    "personal-growth-mentor": "Помогает прояснить цели, выстроить привычки, принять стратегические решения и отслеживать выполнение обязательств.",
    "real-estate-buyer-seller": "Помогает покупателям и продавцам недвижимости: объявления, показы, переговоры, координацию и завершение сделок.",
    "recruitment-specialist": "Организует подбор персонала с учётом китайских кадровых площадок, оценки кандидатов и местного трудового законодательства.",
    "report-distribution-agent": "Распределяет сводные отчёты о продажах между представителями с учётом закреплённых территорий.",
    "resume-tailor": "Адаптирует резюме к вакансии на основе реального опыта; улучшает формулировки и поисковые ключи без выдуманных квалификаций.",
    "retail-customer-returns": "Сопровождает возвраты, обмены и возмещения в торговле с учётом правил, мошенничества и сохранения отношений с клиентами.",
    "sales-data-extraction-agent": "Отслеживает файлы Excel и извлекает показатели продаж за месяц, год и годовой итог для внутренних отчётов.",
    "sales-outreach": "Помогает с первичными контактами B2B, сопровождением обращений, возражениями, предложениями и управлением воронкой.",
    "specialized-chief-of-staff": "Координирует процессы и решения руководителя, фильтрует информацию и готовит результаты для управленческих действий.",
    "specialized-civil-engineer": "Проектирует строительные конструкции и документацию, выполняет расчёты и проверяет международные строительные стандарты.",
    "specialized-codebase-archaeologist": "Находит накопленные расхождения в коде после работы разных ИИ-инструментов: логику, неиспользуемые части и несоответствия документации.",
    "specialized-cultural-intelligence-strategist": "Исследует культурный контекст и скрытое исключение пользователей, чтобы продукт учитывал разные группы и идентичности.",
    "specialized-developer-advocate": "Развивает отношения с разработчиками через сообщества, технический контент и улучшение опыта использования платформы.",
    "specialized-document-generator": "Создаёт документы PDF, PPTX, DOCX и XLSX с помощью кода, правильного оформления, графиков и визуализации данных.",
    "specialized-fedramp-rmf-compliance": "Готовит облачные системы к требованиям FedRAMP и NIST RMF: меры защиты, подтверждения, мониторинг и машинно-читаемые пакеты.",
    "specialized-focus-music-architect": "Проектирует инструментальную музыку для концентрации: запросы к генеративным моделям, звуковые слои и изменение темпа.",
    "specialized-french-consulting-market": "Помогает разобраться во французском рынке ИТ-консалтинга: платформах, ставках, посредниках и сроках оплаты.",
    "specialized-korean-business-navigator": "Объясняет деловую культуру Кореи: согласование решений, иерархию, этикет коммуникации и развитие отношений.",
    "specialized-master-plan-architect": "Обучает архитектуре, критикует риски и создаёт подробные планы реализации в Markdown без выполнения кода.",
    "specialized-mcp-builder": "Проектирует, создаёт и тестирует серверы MCP с инструментами, ресурсами и запросами для расширения возможностей агентов.",
    "specialized-model-qa": "Независимо проверяет модели машинного обучения и статистики: данные, воспроизводимость, калибровку, интерпретацию и отчётность.",
    "specialized-pricing-analyst": "Разрабатывает ценовые модели по данным рынка, конкурентов, затрат и целевой маржинальности.",
    "specialized-salesforce-architect": "Проектирует решения Salesforce: облака, интеграции, ограничения платформы, развёртывание и управление моделью данных.",
    "specialized-strategy-duel-agent": "Проводит стратегические поединки с применением теории игр и тридцати шести китайских стратагем.",
    "specialized-workflow-architect": "Описывает процессы, условия ветвления, ошибки, восстановление, передачу результатов и наблюдаемые состояния для реализации и проверки.",
    "study-abroad-advisor": "Планирует обучение за рубежом для китайских студентов: выбор программ, заявки, эссе, экзамены, визы и адаптацию.",
    "supply-chain-strategist": "Разрабатывает закупочную стратегию и устойчивые цепочки поставок с учётом производителей Китая, качества и цифровизации.",
    "zk-steward": "Ведёт базу знаний по принципам Zettelkasten: отдельные заметки, связи, проверки и поддержку междисциплинарных решений.",
    "support-analytics-reporter": "Анализирует данные, строит панели и отчёты, отслеживает показатели и формулирует выводы для бизнес-решений.",
    "support-executive-summary-generator": "Превращает сложные бизнес-материалы в краткие структурированные сводки для руководителей и принятия решений.",
    "support-finance-tracker": "Контролирует бюджеты, финансовые планы, денежные потоки и показатели эффективности бизнеса.",
    "support-infrastructure-maintainer": "Сопровождает инфраструктуру, повышает её надёжность и производительность и контролирует безопасность и стоимость.",
    "support-legal-compliance-checker": "Проверяет соответствие операций, обработки данных и контента применимым законам, правилам и отраслевым стандартам.",
    "support-support-responder": "Решает обращения пользователей в разных каналах, улучшает поддержку и предупреждает повторные проблемы.",
    "testing-accessibility-auditor": "Проверяет интерфейсы по WCAG и с вспомогательными технологиями; выявляет препятствия для пользователей.",
    "testing-api-tester": "Проверяет контракты, поведение и производительность API, включая взаимодействие систем и внешние интеграции.",
    "testing-evidence-collector": "Собирает снимки экрана и воспроизводимые доказательства ошибок; явно отмечает непроверенные части продукта.",
    "testing-performance-benchmarker": "Измеряет и анализирует производительность приложений и инфраструктуры; предлагает проверяемые улучшения.",
    "testing-reality-checker": "Оценивает готовность продукта по подтверждённым результатам и требует доказательств перед согласованием выпуска.",
    "testing-test-automation-engineer": "Автоматизирует сквозные проверки Playwright и Cypress, устраняет нестабильность и диагностирует ошибки по трассировкам.",
    "testing-test-results-analyzer": "Анализирует результаты тестов и метрики качества; формулирует выводы и действия по обнаруженным проблемам.",
    "testing-tool-evaluator": "Сравнивает и проверяет инструменты, программное обеспечение и платформы для обоснованного выбора в бизнесе.",
    "testing-workflow-optimizer": "Анализирует, улучшает и автоматизирует рабочие процессы для повышения эффективности и производительности.",
}


LEGACY_STARTER_NAMES = {
    "agents-orchestrator": {"Координатор"},
    "project-management-project-shepherd": {"Руководитель проекта"},
    "design-ux-researcher": {"UX-исследователь"},
    "design-ui-designer": {"Дизайнер интерфейса"},
    "engineering-frontend-developer": {"Frontend-разработчик"},
    "engineering-backend-architect": {"Backend-архитектор"},
    "testing-api-tester": {"Тестировщик API"},
    "testing-reality-checker": {"Проверка готовности"},
}


def localized_profile(profile):
    """Add display translations without modifying any original catalog field."""
    return {
        **profile,
        "display_name_ru": role_name_ru(profile["id"], profile["name"]),
        "description_ru": ROLE_DESCRIPTIONS_RU.get(profile["id"], profile.get("description", "")),
    }


def member_name_ru(profile, current_name=""):
    """Only normalize default names; preserve genuine project-specific names."""
    if not current_name or current_name == profile["name"] or current_name in LEGACY_STARTER_NAMES.get(profile["id"], set()):
        return role_name_ru(profile["id"], profile["name"])
    return current_name
