import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const output=fileURLToPath(new URL('../../output/playwright/',import.meta.url));
await mkdir(output,{recursive:true});
const base=process.env.OFFICE_URL||'http://127.0.0.1:4197';
const browser=await chromium.launch({channel:process.env.OFFICE_BROWSER||'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const report={checks:[],accessibility:[],errors:[]};
page.on('pageerror',e=>report.errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});
const check=name=>{report.checks.push(name);console.log('PASS '+name);};
const nav=async name=>page.getByRole('navigation',{name:'Основное меню'}).getByRole('button',{name,exact:true}).click();
const a11y=async name=>{const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();const violations=r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));report.accessibility.push({name,violations});assert.equal(violations.length,0,JSON.stringify(violations));check('Axe '+name);};
const state=async()=>{const r=await context.request.get(base+'/api/state/project-main');assert.ok(r.ok());return r.json();};
try{
  await page.goto(base);
  await nav('Офис');
  await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
  await page.getByRole('heading',{name:'Офис агентов.'}).waitFor();
  await nav('Моя команда');
  const before=await state();
  const originals=before.members.map(m=>({id:m.profile_id,name:m.display_name_ru,tools:m.tools,autonomy:m.autonomy,manager:m.manager_id}));
  if(before.members.length<282){await page.getByRole('button',{name:'Добавить все 282',exact:true}).click();await page.getByText('В КОМАНДЕ: 282',{exact:true}).waitFor();}
  const after=await state();
  assert.equal(after.members.length,282);
  assert.equal(new Set(after.members.map(m=>m.profile_id)).size,282);
  assert.equal(new Set(after.tasks.find(t=>t.demo).stages.map(s=>s.agent_id)).size,8);
  assert.ok(originals.every(m=>{const n=after.members.find(n=>n.profile_id===m.id);return n.display_name_ru===m.name&&n.autonomy===m.autonomy&&JSON.stringify(n.tools)===JSON.stringify(m.tools)&&n.manager_id===m.manager;}));
  check('282 unique members added, original settings preserved, demo still has 8 assignees');
  assert.equal(await page.locator('.member-row').count(),30);
  assert.match(await page.getByLabel('Страницы команды').innerText(),/1–30 из 282/);
  await page.getByLabel('Страницы команды').getByRole('button',{name:'Далее',exact:true}).click();
  assert.match(await page.getByLabel('Страницы команды').innerText(),/31–60 из 282/);
  check('Every member reachable through paginated team');
  await page.getByLabel('Поиск участников команды').fill('engineering-frontend-developer');
  await page.getByLabel('Отдел команды').selectOption('engineering');
  assert.equal(await page.locator('.member-row').count(),1);
  await page.locator('.member-identity').click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('button',{name:'Инструкция',exact:true}).click();
  await dialog.locator('.markdown h1').waitFor();
  assert.match(await dialog.locator('.markdown').innerText(),/Frontend Developer/);
  await page.keyboard.press('Escape');
  check('Search + department filter opens full original instruction');
  await page.getByLabel('Поиск участников команды').fill('qwerty-no-agent');
  await page.getByRole('heading',{name:'Участники не найдены'}).waitFor();
  await page.getByRole('button',{name:'Сбросить фильтры команды'}).click();
  assert.equal(await page.locator('.member-row').count(),30);
  check('Empty search recovers all members');
  await page.getByRole('button',{name:'Новая задача',exact:true}).click();
  const taskForm=page.getByRole('dialog',{name:'Новая задача'});
  const demoIds=new Set(after.tasks.find(t=>t.demo).stages.map(s=>s.agent_id));
  const extra=after.members.find(m=>!demoIds.has(m.profile_id));
  assert.ok(extra);
  await taskForm.getByLabel('Найти исполнителя').fill(extra.profile_id);
  const executorCheckbox=taskForm.locator('.selection-list').first().getByRole('checkbox');
  assert.equal(await executorCheckbox.count(),1);await executorCheckbox.check();
  await taskForm.getByLabel('Название этапа 1',{exact:true}).fill('Этап дополнительного специалиста');
  await taskForm.getByLabel('Найти исполнителя').fill('engineering-frontend-developer');
  await executorCheckbox.check();
  assert.equal(await taskForm.locator('.stage-form-row').count(),2);
  assert.equal(await taskForm.getByLabel('Название этапа 1',{exact:true}).inputValue(),'Этап дополнительного специалиста');
  await a11y('282 executor search form');
  await page.keyboard.press('Escape');
  check('Task form selects a non-demo role and retains stage order across executor searches');
  await nav('Офис');
  await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
  assert.equal(await page.locator('.dept-list .dept-item').count(),18);
  assert.equal(await page.locator('.office-svg .department-summary-node').count(),18);
  assert.ok(await page.locator('.office-svg [tabindex="0"]').count()<50);
  assert.match(await page.locator('.office-heading-meta').innerText(),/282/);
  await a11y('282 office overview');
  await page.screenshot({path:output+'07-all-agents-overview.png',fullPage:true});
  check('18 departments shown without 282 overlapping labels or Tab stops');
  await page.getByRole('button',{name:/^Открыть отдел Разработка(?:,|$)/}).click();
  await page.getByRole('heading',{name:'Разработка.'}).waitFor();
  assert.match(await page.locator('.map-shell').innerText(),/65/);
  const next=page.getByRole('button',{name:/Следующая страница отдела/});
  await next.click();
  assert.match(await page.locator('.map-shell').innerText(),/9–16/);
  await a11y('large department');
  await page.screenshot({path:output+'08-engineering-all.png',fullPage:true});
  check('65 engineering profiles accessible through department pages');
  const repeat=await context.request.post(base+'/api/projects/project-main/members/import-all',{data:{}});
  const repeated=await repeat.json();assert.equal(repeated.added,0);assert.equal(repeated.total,282);
  check('Bulk import repeats safely without duplicates');
  await page.reload();await page.getByRole('heading',{name:'Разработка.'}).waitFor();
  assert.equal((await state()).members.length,282);
  check('282-member team persists after reload');
  await page.setViewportSize({width:390,height:844});
  await nav('Моя команда');
  await page.getByLabel('Поиск участников команды').fill('engineering-backend-architect');
  assert.equal(await page.locator('.member-row').count(),1);
  const dims=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));assert.equal(dims.w,dims.scroll);
  await a11y('282 team mobile search');
  await page.screenshot({path:output+'09-all-agents-mobile.png',fullPage:true});
  check('Mobile search reaches any of 282 members without horizontal overflow');
  await page.setViewportSize({width:1440,height:1000});
  const created=await context.request.post(base+'/api/projects',{data:{name:'Проверка страниц команды '+Date.now(),context:'Изолированный регрессионный тест.'}});
  assert.ok(created.ok());const qa=await created.json();
  const imported=await context.request.post(`${base}/api/projects/${qa.id}/members/import-all`,{data:{}});assert.ok(imported.ok());
  await page.reload();
  await page.getByLabel('Текущий проект').selectOption(qa.id);
  await nav('Моя команда');
  await page.getByText('В КОМАНДЕ: 282',{exact:true}).waitFor();
  const pagination=page.getByLabel('Страницы команды');
  for(let i=0;i<9;i++)await pagination.getByRole('button',{name:'Далее',exact:true}).click();
  assert.match(await pagination.innerText(),/271–282 из 282/);
  const qaState=await (await context.request.get(`${base}/api/state/${qa.id}`)).json();
  for(const member of qaState.members.slice(270)){
    const removed=await context.request.delete(`${base}/api/projects/${qa.id}/members/${member.profile_id}`);assert.ok(removed.ok());
  }
  await page.getByText('В КОМАНДЕ: 270',{exact:true}).waitFor();
  assert.match(await pagination.innerText(),/241–270 из 270/);
  assert.equal(await page.locator('.member-row').count(),30);
  assert.equal(await pagination.getByRole('button',{name:'Далее',exact:true}).isDisabled(),true);
  check('Removing last-page members clamps page and preserves a valid visible range');
  await page.getByLabel('Текущий проект').selectOption('project-main');
  await nav('Офис');
  await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
  assert.deepEqual(report.errors,[]);report.status='passed';
}catch(e){report.status='failed';report.failure=e.stack;await page.screenshot({path:output+'all-agents-failure.png',fullPage:true});console.error(e);process.exitCode=1;}
finally{await writeFile(output+'all-agents-report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length}));}
