import { chromium } from 'playwright';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const output=fileURLToPath(new URL('../../output/playwright/',import.meta.url));
const base=process.env.OFFICE_URL||'http://127.0.0.1:4197';
const browser=await chromium.launch({channel:process.env.OFFICE_BROWSER||'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
await page.goto(base);
await page.getByRole('navigation',{name:'Основное меню'}).getByRole('button',{name:'Офис',exact:true}).click();
await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
await page.getByRole('heading',{name:'Офис агентов.'}).waitFor();
await page.getByText('На связи',{exact:true}).waitFor();
let state=await (await context.request.get(base+'/api/state/project-main')).json();
assert.equal(state.mode,'demo');
let task=state.tasks.find(t=>t.demo);
async function action(name){const r=await context.request.post(`${base}/api/tasks/${task.id}/action`,{data:{action:name,mode:'demo',comment:''}});assert.equal(r.ok(),true,await r.text());task=await r.json();}
if(task.status!=='pending')await action('reset');
await action('start');
for(let i=0;i<7;i++)await action('next');
assert.equal(task.cursor,3);
assert.equal(task.stages[3].status,'running');
await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
await page.locator('.task-summary').getByText('В работе',{exact:true}).waitFor();
await page.locator('.map-status').filter({hasText:'Разработчик клиентской части работает'}).waitFor();
await page.screenshot({path:output+'01-overview.png',fullPage:true});
await page.getByRole('button',{name:/^Открыть отдел Разработка(?:,|$)/}).click();
await page.getByRole('heading',{name:'Разработка.'}).waitFor();
await page.screenshot({path:output+'02-department.png',fullPage:true});
while(task.cursor<task.stages.length)await action('next');
assert.equal(task.status,'awaiting_approval');
await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
await page.getByRole('button',{name:'Принять решение',exact:true}).click();
const dialog=page.getByRole('dialog',{name:'Задача проекта'});
await dialog.getByRole('button',{name:'Повторная проверка Тестировщик API Завершено'}).click();
await dialog.getByRole('heading',{name:'Результат',exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:output+'03-task.png',fullPage:false});
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Принять решение',exact:true}).waitFor();
await page.screenshot({path:output+'10-ready-office.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:output+'04-mobile-office.png',fullPage:true});
await page.getByRole('navigation').getByRole('button',{name:'Моя команда',exact:true}).click();
await page.setViewportSize({width:320,height:740});
await page.screenshot({path:output+'05-mobile-team-320.png',fullPage:true});
await page.getByRole('button',{name:'Новая задача',exact:true}).click();
await page.getByRole('dialog').getByLabel('Название задачи').fill('Подготовить предложение клиенту');
await page.screenshot({path:output+'06-mobile-task-form.png',fullPage:false});
await page.keyboard.press('Escape');
await page.getByRole('navigation').getByRole('button',{name:'Офис',exact:true}).click();
await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
await browser.close();
console.log(JSON.stringify({screenshots:7,project:'project-main',mode:'demo',task_status:task.status,materials_this_run:10}));
