import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const output=fileURLToPath(new URL('../../output/playwright/',import.meta.url));
await mkdir(output,{recursive:true});
const base=process.env.OFFICE_URL||'http://127.0.0.1:4197';
const browser=await chromium.launch({channel:process.env.OFFICE_BROWSER||'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const report={checks:[],accessibility:[],errors:[]};
page.on('pageerror',e=>report.errors.push(e.message));
const check=name=>{report.checks.push(name);console.log('PASS '+name);};
const nav=async name=>page.getByRole('navigation',{name:'Основное меню'}).getByRole('button',{name,exact:true}).click();
const a11y=async name=>{const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();report.accessibility.push({name,violations:result.violations.map(v=>v.id)});assert.deepEqual(result.violations,[]);check('Axe '+name);};
try{
  await page.goto(base);await page.getByText('На связи',{exact:true}).waitFor();
  assert.match(await page.title(),/ИИ-офис/);
  const catalog=await (await page.request.get(base+'/api/catalog')).json();
  assert.equal(catalog.agents.length,282);
  assert.ok(catalog.agents.every(p=>/[А-Яа-яЁё]/.test(p.display_name_ru)&&/[А-Яа-яЁё]/.test(p.description_ru)));
  check('All 282 roles have separate Russian names and descriptions');
  const role=catalog.agents.find(p=>p.id==='engineering-backend-architect');
  await nav('Каталог агентов');
  await page.getByLabel('Поиск профилей').fill(role.display_name_ru);
  assert.equal(await page.locator('.profile-card').count(),1);
  assert.equal(await page.locator('.profile-card h3').innerText(),role.display_name_ru);
  assert.equal(await page.locator('.profile-card > p').innerText(),role.description_ru);
  await page.locator('.profile-card-title').click();
  const dialog=page.getByRole('dialog',{name:'Карточка агента'});
  assert.equal(await dialog.locator('.profile-description').innerText(),role.description_ru);
  check('Russian catalog search opens a fully localized role overview');
  await a11y('Russian role overview');
  await page.screenshot({path:output+'11-russian-profile.png',fullPage:false});
  await dialog.getByRole('button',{name:'Инструкция',exact:true}).click();
  await dialog.locator('.markdown h1').waitFor();
  assert.match(await dialog.locator('.markdown').innerText(),/Backend Architect/);
  assert.equal(await dialog.locator('.markdown').evaluate(el=>el.closest('[lang]')?.getAttribute('lang')),'en');
  check('Original instruction stays intact and has an explicit source language');
  await page.keyboard.press('Escape');
  await page.getByLabel('Поиск профилей').fill(role.id);
  assert.equal(await page.locator('.profile-card').count(),1);
  await nav('Моя команда');await page.getByLabel('Поиск участников команды').fill(role.display_name_ru);
  assert.equal(await page.locator('.member-row').count(),1);
  assert.match(await page.locator('.member-row').innerText(),new RegExp(role.display_name_ru));
  await page.getByRole('button',{name:'Новая задача',exact:true}).click();
  const form=page.getByRole('dialog',{name:'Новая задача'});
  await form.getByLabel('Найти исполнителя').fill(role.display_name_ru);
  assert.equal(await form.locator('.selection-list').first().getByRole('checkbox').count(),1);
  await page.keyboard.press('Escape');
  check('Russian and original-ID searches work in team and executor selection');
  await page.setViewportSize({width:320,height:740});
  const geometry=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));
  assert.ok(geometry.scroll<=geometry.client);
  await a11y('Russian team at 320px');
  check('Long Russian role labels fit the narrow team view');
  assert.deepEqual(report.errors,[]);report.status='passed';
}catch(error){report.status='failed';report.failure=error.stack;await page.screenshot({path:output+'localization-failure.png',fullPage:true});console.error(error);process.exitCode=1;}
finally{await writeFile(output+'localization-report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length}));}
