import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const output=fileURLToPath(new URL('../../output/playwright/',import.meta.url));
await mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:process.env.OFFICE_BROWSER||'msedge',headless:true});
const base=process.env.OFFICE_URL||'http://127.0.0.1:4197';
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const report={started:new Date().toISOString(),checks:[],consoleErrors:[],networkErrors:[],accessibility:[],screenshots:[]};
const expectedErrors=new Set();
page.on('pageerror',e=>report.consoleErrors.push(e.message));
page.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/.test(m.text()))report.consoleErrors.push(m.text());});
page.on('response',r=>{if(r.status()>=400&&!expectedErrors.has(new URL(r.url()).pathname))report.networkErrors.push(`${r.status()} ${r.url()}`);});
page.on('requestfailed',r=>{if(!/ERR_ABORTED/.test(r.failure()?.errorText||''))report.networkErrors.push(r.failure()?.errorText+' '+r.url());});
const check=(name)=>{report.checks.push(name);console.log('PASS '+name);};
const screenshot=async name=>{await page.screenshot({path:output+name,fullPage:true});report.screenshots.push(name);};
const nav=async name=>{await page.getByRole('navigation',{name:'Основное меню'}).getByRole('button',{name,exact:true}).click();};
const overflow=async()=>{
  const geometry=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));
  assert.ok(geometry.scroll<=geometry.client,JSON.stringify(geometry));
};
const a11y=async name=>{
  const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();
  const issues=result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));
  report.accessibility.push({screen:name,violations:issues});
  assert.equal(issues.length,0,'Accessibility '+name+': '+JSON.stringify(issues));
  check('WCAG AA automation: '+name);
};
let qaProject;
try{
  await page.goto(base);
  await nav('Офис');
  await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
  await page.getByRole('heading',{name:'Офис агентов.'}).waitFor();
  await page.getByText('На связи',{exact:true}).waitFor();
  await overflow();
  await screenshot('01-overview.png');
  check('Desktop renders, SSE connected, no page overflow');
  await a11y('office desktop');

  await nav('Каталог агентов');
  await page.getByLabel('Поиск профилей').fill('engineering-frontend-developer');
  await page.getByLabel('Категория каталога').selectOption('engineering');
  assert.equal(await page.locator('.profile-card').count(),1);
  await page.getByRole('button',{name:'Инструкция',exact:true}).click();
  const agentDialog=page.getByRole('dialog',{name:'Карточка агента'});
  await agentDialog.locator('.markdown h1').waitFor();
  assert.match(await agentDialog.locator('.markdown').innerText(),/Frontend Developer/);
  assert.match(await agentDialog.innerText(),/Оригинальная инструкция/);
  check('282 catalog searchable with category; original instruction opens directly');
  await a11y('original profile dialog');
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(),0);
  assert.equal(await page.getByRole('button',{name:'Инструкция',exact:true}).evaluate(el=>el===document.activeElement),true);
  check('Dialog Escape closes and restores focus');

  await nav('Настройки');
  await page.getByRole('button',{name:'Создать другой проект'}).click();
  const newProject=page.getByRole('dialog',{name:'Новый проект'});
  await newProject.getByLabel('Название',{exact:true}).fill('Браузерная проверка '+Date.now());
  await newProject.getByLabel('Контекст',{exact:true}).fill('Изолированный проект проверки интерфейса. Без внешних вызовов.');
  await newProject.getByRole('button',{name:'Создать проект',exact:true}).click();
  await page.getByRole('heading',{name:'Офис агентов.'}).waitFor();
  qaProject=await page.getByLabel('Текущий проект').inputValue();
  assert.notEqual(qaProject,'project-main');
  check('Separate project created with 8 starter members');

  await nav('Каталог агентов');
  await page.getByLabel('Поиск профилей').fill('Anthropologist');
  await page.getByLabel('Категория каталога').selectOption('academic');
  await page.getByRole('button',{name:'В команду',exact:true}).click();
  await page.getByRole('button',{name:'В команде',exact:true}).waitFor();
  await nav('Моя команда');
  assert.equal(await page.locator('.member-row').count(),9);
  await page.locator('.member-row').filter({hasText:'Антрополог'}).getByRole('button').first().click();
  await page.getByRole('dialog').getByRole('button',{name:'Из команды'}).click();
  await page.getByRole('dialog').getByRole('button',{name:'В команду',exact:true}).waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.member-row').count(),8);
  check('Add/remove membership preserves profile in library');

  await nav('Офис');
  await page.getByRole('button',{name:'Открыть отдел Разработка',exact:true}).click();
  await page.getByRole('heading',{name:'Разработка.'}).waitFor();
  assert.equal(await page.locator('.office-svg [data-node][role=button]').count()>0,true);
  await screenshot('02-department.png');
  await overflow();
  check('Department renders tools, agents, processes and department');
  await page.getByRole('button',{name:'Карта связей',exact:true}).click();
  await page.getByRole('button',{name:'Материалы',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Материалы',exact:true}).getAttribute('aria-pressed'),'false');
  await page.getByRole('button',{name:'Материалы',exact:true}).click();
  await page.getByRole('button',{name:'Иерархия',exact:true}).click();
  assert.match(await page.locator('.office-svg').textContent(),/Владелец проекта/);
  check('Graph filters toggle; hierarchy includes owner');
  await page.getByRole('button',{name:'Радиальная карта',exact:true}).click();
  await page.getByRole('button',{name:'Увеличить масштаб',exact:true}).click();
  assert.match(await page.locator('.map-controls').innerText(),/115%/);
  await page.getByRole('button',{name:'Вернуться к общему виду',exact:true}).last().click();
  assert.match(await page.locator('.map-controls').innerText(),/100%/);
  check('Zoom and fit controls work');

  await page.getByRole('button',{name:'Запустить демо',exact:true}).click();
  await page.getByRole('button',{name:'Приостановить шаги',exact:true}).click();
  for(let i=0;i<22;i++){
    const s=await (await context.request.get(`${base}/api/state/${qaProject}`)).json();
    const task=s.tasks[0];
    if(task.status==='awaiting_approval')break;
    assert.equal(task.status,'running');
    const next=page.getByRole('button',{name:'Следующий шаг',exact:true});
    await next.click();
    await page.waitForFunction(()=>!document.querySelector('.task-actions .btn-primary')?.disabled);
  }
  const demoState=await (await context.request.get(`${base}/api/state/${qaProject}`)).json();
  const demo=demoState.tasks[0];
  assert.equal(demo.status,'awaiting_approval');
  assert.equal(demo.stages.filter(s=>s.status==='completed').length,10);
  assert.equal(demoState.materials.filter(m=>m.task_id===demo.id).length,10);
  assert.ok(demoState.materials.filter(m=>m.task_id===demo.id).every(m=>m.example));
  assert.equal(demoState.events.filter(e=>e.action==='revision').length,1);
  assert.equal(demoState.events.filter(e=>e.action==='handoff').length,9);
  check('Full 10-stage demo, 9 handoffs, one concrete revision, examples saved');
  await page.getByRole('button',{name:'Принять решение',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Повторная проверка Тестировщик API Завершено'}).click();
  await screenshot('03-task.png');
  await a11y('task detail and approval');
  await page.getByRole('dialog').getByRole('button',{name:'Согласовать результат',exact:true}).click();
  await page.getByRole('dialog').getByText('Завершено',{exact:true}).first().waitFor();
  const approved=await (await context.request.get(`${base}/api/state/${qaProject}`)).json();
  assert.equal(approved.tasks[0].status,'completed');
  check('Final result stays pending until owner approval');
  await page.keyboard.press('Escape');

  await page.getByRole('button',{name:'Новая задача',exact:true}).first().click();
  const form=page.getByRole('dialog',{name:'Новая задача'});
  await form.getByLabel('Название задачи').fill('Проверить понятность брифа');
  await form.getByLabel('Ожидаемый результат').fill('Краткое заключение и список уточнений.');
  await form.getByLabel('Приоритет').selectOption('high');
  await form.getByLabel('Координатор ИИ-агентов',{exact:true}).check();
  await form.getByLabel('Исследователь пользовательского опыта',{exact:true}).check();
  await form.getByLabel('Название этапа 1').fill('Сформулировать критерии');
  await form.getByLabel('Название этапа 2').fill('Проверить бриф');
  await form.getByLabel('Условия завершения').fill('Два согласованных материала.');
  await a11y('new task form');
  await form.getByRole('button',{name:'Создать задачу',exact:true}).click();
  await page.getByRole('heading',{name:'Задачи.'}).waitFor();
  assert.match(await page.locator('.task-cards').innerText(),/Проверить понятность брифа/);
  await page.reload();
  await page.getByRole('heading',{name:'Офис агентов.'}).waitFor();
  const persisted=await (await context.request.get(`${base}/api/state/${qaProject}`)).json();
  const custom=persisted.tasks.find(t=>t.title==='Проверить понятность брифа');
  assert.deepEqual(custom.stages.map(s=>s.name),['Сформулировать критерии','Проверить бриф']);
  assert.equal(custom.priority,'high');
  assert.equal(custom.completion,'Два согласованных материала.');
  check('Task creation persists ordered named stages, priority and completion criteria');

  await nav('Настройки');
  expectedErrors.add('/api/settings/mode');
  await page.getByRole('radio',{name:/Подключённая модель/}).click();
  await page.getByRole('alert').filter({hasText:'Модель не подключена'}).waitFor();
  assert.equal(await page.getByRole('radio',{name:/Демонстрация/}).isChecked(),true);
  check('Unavailable model reports error; demo is not silently substituted');

  await page.setViewportSize({width:390,height:844});
  await nav('Офис');
  await overflow();
  await screenshot('04-mobile-office.png');
  await a11y('office mobile 390');
  await nav('Моя команда');
  await overflow();
  assert.equal(await page.locator('.member-row').count(),8);
  check('Mobile has accessible team list without requiring map panning');
  await page.setViewportSize({width:320,height:740});
  await overflow();
  await screenshot('05-mobile-team-320.png');
  await nav('Офис');
  await overflow();
  await page.getByRole('button',{name:'Новая задача',exact:true}).click();
  await page.getByRole('dialog').getByLabel('Название задачи').fill('Мобильная проверка');
  await overflow();
  const dialogBounds=await page.getByRole('dialog').boundingBox();
  assert.ok(dialogBounds.x>=0&&dialogBounds.x+dialogBounds.width<=320);
  await page.getByRole('dialog').getByRole('button',{name:'Создать задачу'}).scrollIntoViewIfNeeded();
  await screenshot('06-mobile-task-form.png');
  await page.keyboard.press('Escape');
  check('320px team and long modal scroll fit; footer remains reachable');

  assert.deepEqual(report.consoleErrors,[]);
  assert.deepEqual(report.networkErrors,[]);
  check('No browser exceptions or unexpected network failures');
  report.status='passed';
}catch(error){
  report.status='failed';report.failure=error.stack;
  await page.screenshot({path:output+'failure.png',fullPage:true}).catch(()=>{});
  console.error(error);
  process.exitCode=1;
}finally{
  report.finished=new Date().toISOString();report.project_id=qaProject;
  await writeFile(output+'browser-report.json',JSON.stringify(report,null,2));
  await browser.close();
  console.log(JSON.stringify({status:report.status,checks:report.checks.length,report:output+'browser-report.json'}));
}
