import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const output = fileURLToPath(new URL('../../output/playwright/', import.meta.url));
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: process.env.OFFICE_BROWSER || 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
await page.goto(process.env.OFFICE_URL || 'http://127.0.0.1:4197');
await page.getByRole('heading',{name:'Офис агентов.'}).waitFor();
await page.getByText('На связи',{exact:true}).waitFor();
await page.screenshot({path:output+'01-overview.png',fullPage:true});
await writeFile(output+'initial-dom.txt',await page.locator('body').innerText(),'utf8');
console.log(JSON.stringify({errors,overflow:await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth})),output}));
await browser.close();
